In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

In [3]:
# 判断是否处于eager模式
tf.executing_eagerly()

True

In [5]:
# 在Eager模式下立刻出结果
x = [[2,]]

In [7]:
# 矩阵相乘
m = tf.matmul(x, x)

In [8]:
# tensor张量高维数组，张量是不可变，可以存在GPU上
print(m)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [9]:
m.numpy()

array([[4]])

In [10]:
# 建立一个常量
a = tf.constant([[1, 2],
                [3, 4]])

In [11]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [12]:
a.numpy()

array([[1, 2],
       [3, 4]])

In [14]:
b = tf.add(a, 1)

In [15]:
# 加法自动广播
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [19]:
c = tf.multiply(a,b)

In [20]:
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]])>

In [17]:
import numpy as np

In [21]:
d = np.array([[5,6], 
              [7, 8]])

In [22]:
d

array([[5, 6],
       [7, 8]])

In [24]:
(a + b).numpy()

array([[3, 5],
       [7, 9]])

In [26]:
g = tf.convert_to_tensor(10)

In [27]:
g

<tf.Tensor: id=63, shape=(), dtype=int32, numpy=10>

In [28]:
float(g)

10.0

In [14]:
c = tf.multiply(a, b)

In [15]:
c

<tf.Tensor: id=11, shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]])>

In [16]:
num = tf.convert_to_tensor(10)

In [17]:
num

<tf.Tensor: id=13, shape=(), dtype=int32, numpy=10>

In [18]:
for i in range(num.numpy()):
    i = tf.constant(i)
    if int(i%2) == 0:
        print('even')
    else:
        print('odd')

even
odd
even
odd
even
odd
even
odd
even
odd
