In [1]:
import tensorflow as tf

In [2]:
print('Tensorflow version: {}'.format(tf.__version__))

Tensorflow version: 2.2.0


In [3]:
# 使用列表创建一个dataset
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6, 7])

In [4]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [10]:
# 直接对他进行迭代
for ele in dataset:
    print(ele.numpy())

1
2
3
4
5
6
7


In [11]:
# 使用二维列表，形状要相同，三个元素，每个长度为2 
dataset = tf.data.Dataset.from_tensor_slices([[1, 2], [3, 4], [5, 6]])

In [12]:
dataset

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [10]:
for ele in datase t:
    print(ele.numpy())

[1 2]
[3 4]
[5 6]


In [11]:
# 使用字典
dataset_dic = tf.data.Dataset.from_tensor_slices({'a': [1,2,3,4],
                                                  'b': [6,7,8,9],
                                                  'c': [12,13,14,15]
    
})

In [13]:
dataset_dic

<TensorSliceDataset shapes: {a: (), b: (), c: ()}, types: {a: tf.int32, b: tf.int32, c: tf.int32}>

In [14]:
for ele in dataset_dic:
    print(ele)

{'a': <tf.Tensor: id=60, shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: id=61, shape=(), dtype=int32, numpy=6>, 'c': <tf.Tensor: id=62, shape=(), dtype=int32, numpy=12>}
{'a': <tf.Tensor: id=66, shape=(), dtype=int32, numpy=2>, 'b': <tf.Tensor: id=67, shape=(), dtype=int32, numpy=7>, 'c': <tf.Tensor: id=68, shape=(), dtype=int32, numpy=13>}
{'a': <tf.Tensor: id=72, shape=(), dtype=int32, numpy=3>, 'b': <tf.Tensor: id=73, shape=(), dtype=int32, numpy=8>, 'c': <tf.Tensor: id=74, shape=(), dtype=int32, numpy=14>}
{'a': <tf.Tensor: id=78, shape=(), dtype=int32, numpy=4>, 'b': <tf.Tensor: id=79, shape=(), dtype=int32, numpy=9>, 'c': <tf.Tensor: id=80, shape=(), dtype=int32, numpy=15>}


In [15]:
import numpy as np

In [16]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5, 6, 7]))

In [19]:
# 取出前四个
for ele in dataset.take(4):
    print(ele.numpy())

1
2
3
4


In [22]:
next(iter(dataset.take(1)))

<tf.Tensor: id=146, shape=(), dtype=int32, numpy=1>

In [23]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [31]:
dataset = dataset.shuffle(7)
dataset = dataset.repeat()
dataset = dataset.batch(3)

In [32]:
for ele in dataset:
    print(ele.numpy())

[6 5 4]
[2 2 7]
[6 1 4]
[5 7 1]
[5 3 3]
[2 6 4]
[7 1 3]
[7 4 1]
[3 6 3]
[7 5 2]
[2 1 4]
[6 7 2]
[4 1 5]
[5 6 3]
[4 3 6]
[7 7 2]
[6 5 1]
[5 4 6]
[1 5 3]
[4 2 1]
[2 7 3]


In [33]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5, 6, 7]))

In [34]:
dataset = dataset.map(tf.square)

In [35]:
for ele in dataset:
    print(ele.numpy())

1
4
9
16
25
36
49
